"""Puertos (interfaces) de persistencia. La capa de aplicación depende de estos Protocols,
no de implementaciones concretas: así se invierte la dependencia y se pueden inyectar fakes
en los tests (principio V de la constitución).
"""

from __future__ import annotations

from typing import Protocol

from .dto import GameEntity, MoveEntity, PlayerEntity


class PlayerRepository(Protocol):
    async def add(self, player: PlayerEntity) -> PlayerEntity: ...
    async def get_by_id(self, player_id: int) -> PlayerEntity | None: ...
    async def get_by_username(self, username: str) -> PlayerEntity | None: ...
    async def update(self, player: PlayerEntity) -> None: ...
    async def list_all(self) -> list[PlayerEntity]: ...


class GameRepository(Protocol):
    async def add(self, game: GameEntity) -> GameEntity: ...
    async def get(self, game_id: int) -> GameEntity | None: ...
    async def list_for_player(self, player_id: int) -> list[GameEntity]: ...
    async def update(self, game: GameEntity) -> None: ...


class MoveRepository(Protocol):
    async def add(self, move: MoveEntity) -> MoveEntity: ...
    async def list_for_game(self, game_id: int) -> list[MoveEntity]: ...
    async def count_for_game(self, game_id: int) -> int: ...
